### ISSUE TITLE
Support 12 word BIP39 mnemonics

### ISSUE THREAD

**Issue by hodlwave** [hodlwave/proof-wallet#1]
Add a `--num-words` CLI argument to the `create-wallet` program that allows 12 and 24 (default) word BIP39 mnemonics.

(as requested by @Fonta1n3 in https://github.com/hodlwave/proof-wallet-v1/issues/3)

**Comment by Fonta1n3** [comment]
That would be nice! At BlockchainCommons we are implementing a great shamir secret sharding library that is compatible with BIP39 (SLIP39 is *not*). Sharding three sets of 24 word seeds is too much work, 12 words is a nice compromise. Also FN and Gordian Wallet use 12 words mnemonics for multisig by default.

**Comment by hodlwave** [comment]
I see, interesting. Out of curiosity, the input to the SSS is a 12 word mnemonic, but in what form are the N output shards?

**Comment by Fonta1n3** [comment]
I believe the idea is to use [byte words](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-012-bytewords.md).

**Comment by hodlwave** [comment]
Support for 12 word BIP39 mnemonics added for...
`create-wallet`: https://github.com/hodlwave/proof-wallet/commit/880855086cefd6e17d867bea0b3970cd596183de
`view-addresses` / `sign-psbt`: https://github.com/hodlwave/proof-wallet/commit/8ee280324484b078f20f80c6c99150aed8fd94d4

Feel free to play around with it on testnet; will resolve this issue once I've implemented full test coverage.

**Comment by hodlwave** [comment]
c066d47684715eb43332c36d829f288ef12e6140 adds test coverage for both 12 and 24 word BIP39 mnemonics. Note that I still need to update the tests for both `view-addresses` and `sign-psbt` programs.
