### ISSUE TITLE
Quickstart has incomplete Bitcoin Core verification

### ISSUE THREAD

**Issue by bitcoinhodler** [hodlwave/proof-wallet#4]
The Quickstart doc verifies the signature on the SHA256SUMS file, but it doesn't run `sha256sum` to verify that the binary actually matches!

Like so:
```
$ sha256sum -c --ignore-missing SHA256SUMS.asc
bitcoin-0.19.0.1-x86_64-linux-gnu.tar.gz: OK
sha256sum: WARNING: 20 lines are improperly formatted
```

**Comment by hodlwave** [comment]
Sorry, just seeing this now. Fixed by 4e29fec19f91cdf9f7f6c17c943820bcd887ece1.
